name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        auto-update-conda: true
        update-conda: true
        conda-channels: conda-forge

    - name: Conda install dependencies
      run: conda install nodejs

    - name: Test install
      run: npm install && npm run build
